version: "3"
services:
  firebase:
    image: itscow:vuetify
    ports:
      - 9005:9005
      - 5000:5000
      - 8080:8080
      - 5001:5001
      - 8888:8888 # Webpack Bundle Analyzer
      - 8000:8000 # Vue UI
    environment:
      - HOST=0.0.0.0
    expose:
      - 5000
    volumes:
      - ./:/app
    tty: true
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
